# Generated by Django 6.0.3 on 2026-03-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=70)),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('cor', models.CharField(max_length=20)),
                ('data_fabricacao', models.DateField()),
                ('imagem', models.CharField(max_length=25)),
            ],
        ),
    ]
